#!/bin/bash
# SessionStart hook — loads a project context generated by /prepare-project-for-agent.
#
# Resolves basename "$PWD" -> ~/.claude/project-contexts/<slug>/README.md and
# injects it at session start. Also scans */.git sub-repos (monorepos) and loads
# any matching context. Raw `cat` only: no link is followed, no path resolved —
# everything that must reach the agent has to be in the README itself.
#
# Always emits an acknowledge instruction so the user sees in the CLI what loaded.

CTX_BASE="$HOME/.claude/project-contexts"

if [ -d "$CTX_BASE" ]; then
  CWD_SLUG=$(basename "$PWD")
  DIRECT="$CTX_BASE/$CWD_SLUG/README.md"
  SUB_READMES=()
  shopt -s nullglob
  for subdir in "$PWD"/*/; do
    [ -d "${subdir}.git" ] || continue
    sub_basename=$(basename "$subdir")
    sub_readme="$CTX_BASE/$sub_basename/README.md"
    [ -f "$sub_readme" ] && SUB_READMES+=("$sub_basename")
  done
  shopt -u nullglob

  if [ -f "$DIRECT" ] || [ ${#SUB_READMES[@]} -gt 0 ]; then
    echo "[SESSION INSTRUCTION] Begin your first reply with exactly: \"Project context loaded.\""
    echo
    echo "# Project context (loaded by /prepare-project-for-agent)"
    echo
    if [ -f "$DIRECT" ]; then
      echo "## $CWD_SLUG"
      echo
      cat "$DIRECT"
      echo
    fi
    for sub in "${SUB_READMES[@]}"; do
      echo "## $sub (sub-repo)"
      echo
      cat "$CTX_BASE/$sub/README.md"
      echo
    done
    exit 0
  fi
fi

# No context for this directory.
echo "[SESSION INSTRUCTION] Begin your first reply with exactly: \"No project context.\""
exit 0
